/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Agenda: () => import('#controllers/agenda_controller'),
  Counters: () => import('#controllers/counters_controller'),
  Journal: () => import('#controllers/journal_controller'),
  Session: () => import('#controllers/session_controller'),
  Shoppings: () => import('#controllers/shoppings_controller'),
  Todays: () => import('#controllers/todays_controller'),
}
