/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AgendaItemCompletionSchema extends BaseModel {
  static $columns = ['id', 'agendaItemId', 'occurrenceDate', 'completedAt', 'createdAt'] as const
  $columns = AgendaItemCompletionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare agendaItemId: number
  @column.date()
  declare occurrenceDate: DateTime
  @column.dateTime()
  declare completedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AgendaItemPauseSchema extends BaseModel {
  static $columns = ['id', 'agendaItemId', 'startedAt', 'endedAt', 'createdAt', 'updatedAt'] as const
  $columns = AgendaItemPauseSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare agendaItemId: number
  @column.date()
  declare startedAt: DateTime
  @column.date()
  declare endedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AgendaItemSchema extends BaseModel {
  static $columns = ['id', 'userId', 'title', 'dayMoment', 'category', 'startDate', 'endDate', 'recurrenceType', 'recurrenceUnit', 'recurrenceInterval', 'weekDays', 'isActive', 'createdAt', 'updatedAt', 'startHour'] as const
  $columns = AgendaItemSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare title: string
  @column()
  declare dayMoment: any
  @column()
  declare category: any
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare recurrenceType: any
  @column()
  declare recurrenceUnit: any | null
  @column()
  declare recurrenceInterval: number | null
  @column()
  declare weekDays: any | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare startHour: number | null
}

export class CounterSchema extends BaseModel {
  static $columns = ['id', 'userId', 'pinned', 'title', 'direction', 'trigger', 'initialValue', 'value', 'color', 'createdAt', 'updatedAt', 'lastAppliedDate'] as const
  $columns = CounterSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare pinned: boolean
  @column()
  declare title: string
  @column()
  declare direction: string
  @column()
  declare trigger: string
  @column()
  declare initialValue: number
  @column()
  declare value: number
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.date()
  declare lastAppliedDate: DateTime | null
}

export class JournalSchema extends BaseModel {
  static $columns = ['id', 'userId', 'entryDate', 'mood', 'content', 'createdAt', 'updatedAt'] as const
  $columns = JournalSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column.date()
  declare entryDate: DateTime
  @column()
  declare mood: any
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'hash', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare hash: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ShoppingSchema extends BaseModel {
  static $columns = ['id', 'userId', 'name', 'category', 'pinned', 'done', 'createdAt', 'updatedAt'] as const
  $columns = ShoppingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare name: string
  @column()
  declare category: any
  @column()
  declare pinned: boolean
  @column()
  declare done: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
